### ISSUE TITLE
Disable EmptyView

### ISSUE THREAD

**Issue by Licantrop0** [roubachof/Sharpnado.TaskLoaderView#1]
Hi, my CollectionView already has an EmptyView, and I would like to use that one because it also has a header to add items that I would like to keep.
How do I disable the EmptyView in the TaskLoaderView so that it will always display the content even if there are no items?

thanks!

**Comment by Licantrop0** [comment]
I resolved by adding
`FoodsLoader.ShowResult = true;`
after 
`FoodsLoader.Load(GetFoods);`

in the ViewModel constructor, but I don't know if it's the right thing.

**Comment by roubachof** [comment]
fixed since https://github.com/roubachof/Sharpnado.TaskLoaderView/releases/tag/v2.1.0
