### ISSUE TITLE
ErrorNotificationView=snackbar as separate nuget package

### ISSUE THREAD

**Issue by sebfrie** [roubachof/Sharpnado.TaskLoaderView#10]
Hi! I really like your whole TaskLoaderView concept and love the sheer amount of features built into it.

However, is there a possibility to get the ErrorNotificationView as nice separate "snackbar" component? Or is there already an option to use it outside of the TaskLoaderView context?

Thanks!

**Comment by roubachof** [comment]
Yup it's planned :)

**Comment by roubachof** [comment]
snackbar is now a separate component
