### ISSUE TITLE
IGDB API is obsolete

### ISSUE THREAD

**Issue by SailorTurkey** [roubachof/Sharpnado.TaskLoaderView#11]
I found out your library a while ago. Wanted to give it a go, to my luck, IGDB API is obsolete now :)

 "These changes mean that there is some effort required to transition off the v3 API, which will be shut down on 26th October, 2020."
New API is located at URL with authorization too changed.

I know it might be a pain to update Retronado now, just wanted give a heads up :)

https://api.igdb.com/v4

**Comment by roubachof** [comment]
ARRRGGHHHH

**Comment by roubachof** [comment]
migration to v4 done :)
