### ISSUE TITLE
[Question] various tasks

### ISSUE THREAD

**Issue by angelru** [roubachof/Sharpnado.TaskLoaderView#12]
I am using shell navigation and this is my scenario:
     
```
            var vm = new ChatMessagesPageViewModel
            {
                ChatRoom = _selectedChat
            };

            var page = new ChatMessagesPage
            {
                BindingContext = vm
            };

            await Shell.Current.Navigation.PushAsync(page);

  public ChatRoom ChatRoom
        {
            get => _chatRoom;
            set
            {
                _chatRoom = value;
                 ChatMessagesLoader.Load(InitMessagesAsync);
            }
        }

 public async Task InitMessagesAsync()
        {
            if (!_chatRoom.IsPrivate)
            {
                var cleanIds = _chatRoom.UserIds.Except(users.Keys);

                if (cleanIds.Any())
                {
                    await Task.WhenAll(cleanIds.Select(async id =>
                    {
                        var user = await ApiRest.UserAsync(id);
                        users.Add(id, user.Name);
                    }));
                }
            }

            var employes =  await ApiRest.ChatMessagesAsync();
}
```

the problem is that there is a flickering of the ActivityIndicator and as a freeze of the ui in the navigation, if I deactivate the animation this does not happen. I don't know if it has to do with your component or how I execute the tasks.

**Comment by roubachof** [comment]
I don't know, I have too little info to say anything about your issue.
Maybe try call Load in the `OnAppearing` method instead of the setter.

**Comment by angelru** [comment]
The same thing happens, removing the animation or putting a delay seems to work fine. If you need more information tell me

**Comment by roubachof** [comment]
I'm afraid it's not an issue with `TaskLoaderView`, the issue here is seem to be that you are doing 2 heavy thing at the same time. Maybe the the Load occurs at the same time as your navigation. Or it occurs at the same time as a complex UI being built.
