### ISSUE TITLE
How to bind TaskLoaderView.LoadingView visibility to TaskLoaderNotifier.ShowRefresher?

### ISSUE THREAD

**Issue by aezakmi8** [roubachof/Sharpnado.TaskLoaderView#13]
How to bind TaskLoaderView.LoadingView visibility to TaskLoaderNotifier.ShowRefresher?

To just swap between Views insted of skeletonLoading each item in CollectionView.ResultView

![Screenshot](https://user-images.githubusercontent.com/24376117/170657295-7f45b8ca-1cfb-4735-b9a4-3b2df3b60d3f.JPG)

`
<ContentView>
                <customViews:TaskLoaderView x:Name="TaskLoaderStyle"
                                            Grid.Row="2" 
                                            TaskLoaderNotifier="{Binding StockLoader}"
                                            Style="{StaticResource TaskLoaderStyle}">
                    <customViews:TaskLoaderView.LoadingView>
                        <sho:CollectionView BackgroundColor="Transparent" 
                                            sk:Skeleton.IsBusy="{Binding StockLoader.ShowRefresher}"
                                            sk:Skeleton.IsParent="True"
                                            sk:Skeleton.BackgroundColor="{StaticResource TosWindows}"
                                            sk:Skeleton.Animation="{sk:DefaultAnimation Fade}"
                                            ItemsSource="{x:Static model:Skeletons.StockPlaceHolder}"
                                            ItemTemplate="{StaticResource StockViewCell}" CollectionLayout="Grid" SnapStyle="Center" ColumnCount="2" ScrollSpeed="Normal" ItemSpacing="20" ItemWidth="170" ItemHeight="300" Style="{StaticResource CollectionView}">
                        </sho:CollectionView>
                    </customViews:TaskLoaderView.LoadingView>
                    <customViews:TaskLoaderView.ResultView>
                        <RefreshView Command="{Binding StockLoader.RefreshCommand}"
                                 IsRefreshing="{Binding StockLoader.ShowRefresher}"
                                 RefreshColor="{StaticResource AccentColor}">
                            <sho:CollectionView CurrentIndex="{Binding CurrentIndex}"
                                            BackgroundColor="Transparent" 
                                            ItemsSource="{Binding StockLoader.Result}" 
                                            ItemTemplate="{StaticResource StockViewCell}" CollectionLayout="Grid" SnapStyle="Center" ColumnCount="2" ScrollSpeed="Normal" ItemSpacing="20" ItemWidth="170" ItemHeight="300" Style="{StaticResource CollectionView}">
                            </sho:CollectionView>
                        </RefreshView>
                    </customViews:TaskLoaderView.ResultView>
                </customViews:TaskLoaderView>
            </ContentView>
`

**Comment by roubachof** [comment]
You can use the `TaskLoaderType="ResultAsLoadingView"` property, and get rid of the LoadingView.
If you want to show skeleton when loading from scratch OR refreshing, I guess you will have to use multi binding with ShowRefresher and ShowLoader on the Skeleton.IsBusy property:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/multibinding

**Comment by aezakmi8** [comment]
Thanks for the answer.
I'll try :3
