### ISSUE TITLE
Build with .NET MAUI

### ISSUE THREAD

**Issue by naaeef** [roubachof/Sharpnado.TaskLoaderView#14]
**Platform:**
 - OS: Both
 - Device: iPhoneSimulator, AndroidEmulator
 - Sdk vervion: 7.0.52/7.0.100
 - .NET MAUI
 - Visual Studio 17.4.3

**Describe the bug**
As soon as I add the NuGet package (v. 2.5.1) to a new .NET MAUI project with the default template, the app does not compile anymore for iOS or Android.

**To Reproduce**
Steps to reproduce the behavior (see also attached [Reproduction sample.zip](https://github.com/roubachof/Sharpnado.TaskLoaderView/files/10372527/Reproduction.sample.zip)):
1. Create a new .NET MAUI project
2. Add NuGet Sharpnado.TaskLoaderView, version 2.51
3. Build project for Android or iOS

**Exceptions**
```
1>App.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Application".
1>App.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Application".
1>AppShell.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Shell".
1>AppShell.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "Shell".
1>MainPage.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ContentPage".
1>MainPage.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ContentPage".
1>Resources\Styles\Colors.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
1>Resources\Styles\Colors.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
1>Resources\Styles\Styles.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
1>Resources\Styles\Styles.xaml : error :  : XamlC error XFC0000 : Cannot resolve type "ResourceDictionary".
```

**Comment by roubachof** [comment]
You are adding the wrong package, you need to add the maui flavor.
I added an installation section to make it clearer:
https://github.com/roubachof/Sharpnado.TaskLoaderView#maui

**Comment by naaeef** [comment]
Thank you for your help!
