### ISSUE TITLE
how implemenet in maui skeleton?

### ISSUE THREAD

**Issue by HectorOCH** [roubachof/Sharpnado.TaskLoaderView#15]
how to implement skeleton on maui.net i couldn't figure out the example

**Comment by roubachof** [comment]
It's in the sample app

**Comment by HectorOCH** [comment]
Maybe it's easy but in retronado.Maui I can't find Maui.Skeleton

**Comment by roubachof** [comment]
Guys from horus didnt port to maui... for now you have to reference the fork.
I will try to make a nuget package for maui.

**Comment by roubachof** [comment]
Horus merged my PR
