### ISSUE TITLE
TaskLoaderView  showloader

### ISSUE THREAD

**Issue by angelru** [roubachof/Sharpnado.TaskLoaderView#5]
Hey man!!

I have other question ... 

I am using firebase and there is no async on listeners, for example:

    query = CrossCloudFirestore.Current.Instance.GetCollection(Settings.ItemsCollection)
                                                  .WhereGreaterThanOrEqualsTo("Date", DateTime.Now.Date)
                                                  .OrderBy("Date", true).LimitTo(limitItems);

            query.AddSnapshotListener((snapshot, error) =>
            {
                ItemsLoader.ShowLoader = true;
                QuerySnapshot(snapshot);
                ItemsLoader.ShowLoader = false;
            });

does not show the loader, its possible???

**Comment by angelru** [comment]
Can be done ?

**Comment by roubachof** [comment]
Hey man, sorry for the delay, busy as hell lately...
`TaskLoaderNotifier` is based on Task, so you need to wrap your QuerySnapshot in a Task:

```csharp
private Task QuerySnapshotAsync()
{
    return Task.Run(() => QuerySnapshot(snapshot));
}
```

then use the TaskLoaderNotifier normally

```csharp
query.AddSnapshotListener((snapshot, error) =>
        {
            ItemsLoader.Load(QuerySnapshotAsync);
        });
```

**Comment by angelru** [comment]
wowww! it works! many thanks!
It is an excellent library
