### ISSUE TITLE
TaskLoaderCommand Doesn't accept Tasks with parameters

### ISSUE THREAD

**Issue by clifzero** [roubachof/Sharpnado.TaskLoaderView#6]
HI Jean,

Thank you for the wonderful plugin, I absolutely love it!!!

One question though, Is there any specific reason why there's no support for Func<T, Task>, I wanted to assign a Task with a parameter to TaskLoaderCommand, but I couldn't because it only accepts Func<Task> in the constructor.

**Comment by roubachof** [comment]
Happy you like it! Don't tell it but it's my favorite one 😂. It is fixed since 2.1 that I uploaded to nuget yesterday

**Comment by roubachof** [comment]
One more thing: it supports now DataTemplate for its custom views: https://github.com/roubachof/Sharpnado.TaskLoaderView#support-for-datatemplate-since-210

So you can define your views once in a resources dictionary.

**Comment by clifzero** [comment]
Don't worry, I won't tell it🤫😁.
Thank you soooo much Jean, you're the absolute bomb!
