### ISSUE TITLE
How to handle Visual State Management with TaskLoaderView ?

### ISSUE THREAD

**Issue by Kapusch** [roubachof/Sharpnado.TaskLoaderView#7]
Hello @roubachof ,

First of all, thank you for all the examples you provide about implementing your libraries.

I have tried to import your TaskLoaderView in my project, but the app crashed for every page where I have an existing [VisualStateManager](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager) code.

This is the error I've got when **InitializeComponent()** is executed to build the View :
_System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null._

_Parameter name: targetObject
  at Xamarin.Forms.Setter.Apply (Xamarin.Forms.BindableObject target, System.Boolean fromStyle) [0x00027] in D:\a\1\s\Xamarin.Forms.Core\Setter.cs:58 
  at Xamarin.Forms.VisualStateManager.GoToState (Xamarin.Forms.VisualElement visualElement, System.String name) [0x000b9] in D:\a\1\s\Xamarin.Forms.Core\VisualStateManager.cs:90 
  at Xamarin.Forms.VisualStateGroup.UpdateStateTriggers () [0x00029] in D:\a\1\s\Xamarin.Forms.Core\VisualStateManager.cs:437_ 
...

Crash happens only if I have VisualStateManager inside the TaskLoaderView component.
But when I move it outside, VisualStateManager is like "deactivated" and no state are applied.

- Did you try to set a TaskLoaderView component in a page where you have VisualState management ?

If yes, could you please provide an example ?

Thank you in advance for your time !

**Comment by roubachof** [comment]
Interesting...
I must say I don't like too much VisualStateManager as I find them so verbose, and the GoToState pattern is not exactly my thing :)
A repro sample could be helpful in this case.

**Comment by Kapusch** [comment]
> A repro sample could be helpful in this case.

Sure, I will as soon as possible !

**Comment by Kapusch** [comment]
Hi again @roubachof , here is the [demo project](https://github.com/Kapusch/XF_Bug_TaskLoaderView_VisualStateManager) showing the System.ArgumentNullException (Parameter name: targetObject).

Loading "QuoteDetails" View shows an animation during 1,5s before to display the page.
In this page, you will be able to switch a state via a toggle button in order to update text color from black to blue.

I have voluntarily commented your TaskLoaderView component in [QuoteDetailPage.xaml](https://github.com/Kapusch/XF_Bug_TaskLoaderView_VisualStateManager/blob/master/GreatQuotes/QuoteDetailPage.xaml) in order to let you have a first try, without any crash.

But if you uncomment the TaskLoaderView, you will be able to observe the exception.

Thanks a lot for your help !

**Comment by Kapusch** [comment]
For information, I have reproduced the same error, without your component TaskLoaderView, by just setting a wrong "TargetName" value for a Setter (inside VisualState.Setters).

Error is throwed [here in Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Core/Setter.cs#L58).

It's like the [ResultView container](https://github.com/roubachof/Sharpnado.TaskLoaderView/blob/master/Sharpnado.TaskLoaderView/TaskLoaderView.xaml#L47) does not handle yet my view and hence, no element of my view is targettable by a VisualState Setter.

1. Is there something possible to adapt in your library ?
2. Or do I have somehow to wait for my view to be loaded by your component before to execute InitializeComponent and generate the view ?

All my views do implement VisualStates, then I am currently not able to go further, but I would love to use your library in my project !

What do you think @roubachof ?

**Comment by roubachof** [comment]
Just spent 2 hours trying to figure out what's happening and I cannot wrap my head around it...
All is indeed nicely initialized when the BindingContext is propagated so I'm clueless :/

I will try to reach the XF team on this matter to see if anyone could help :)

**Comment by Kapusch** [comment]
Thank you for your involvement on this matter, I really do hope that you will find some clues on it !

**Comment by Kapusch** [comment]
Hello @roubachof , did you find some clues on this ?

I would really appreciate using your library in my app before I release it.

**Comment by roubachof** [comment]
This issue disappears if you use the `TemplatedTaskLoader` which is now the preferred version to handle your states:
https://github.com/roubachof/Sharpnado.TaskLoaderView#250-maui-support-o-and-templatedtaskloader
