### ISSUE TITLE
TaskLoaderCommand CanExecute Not Working Properly

### ISSUE THREAD

**Issue by clifzero** [roubachof/Sharpnado.TaskLoaderView#9]
**Platform (please complete the following information):**
 - OS: Android
 - Device: Huawei P20 Lite
 - Sdk vervion: [Android SDK 21]
 - Xamarin.Forms: [4.4.0.991477]

**Describe the bug**
TaskLoaderCommand throws an exception if RaiseCanExecuteChanged is called before the task is ran, which is when one would typically call RaiseCanExecuteChanged, before and after processing is done. Also causes weird behavior when Command is bound to ToobarItem Command property.

**To Reproduce**
 [Here's](https://www.dropbox.com/s/aeezua1ol7u3rj5/sample_application.zip?dl=0) a sample application that reproduces the issue.

**Comment by roubachof** [comment]
this has been resolved, and you will get some cool functionalities like `AutoRaiseCanExecuteChanged`:

        public async void Execute(object parameter)
        {
            if (IsExecuting)
            {
                return;
            }

            try
            {
                IsExecuting = true;

                if (AutoRaiseCanExecuteChange)
                {
                    RaiseCanExecuteChanged();
                }

                ExecuteInternal(parameter);

                // TaskCompleted special task never raise an exception, so we are safe with async void ;)
                await Notifier.CurrentLoadingTask.TaskCompleted;
            }
            finally
            {
                IsExecuting = false;
                if (AutoRaiseCanExecuteChange)
                {
                    RaiseCanExecuteChanged();
                }
            }
        }

**Comment by PauchardThomas** [comment]
Can you provide a new nuget release ?

**Comment by roubachof** [comment]
@PauchardThomas @Cliffy786 Could you try this beta version and see if it rocks your boat :) ?
[Sharpnado.TaskLoaderView.2.2.0.nupkg.zip](https://github.com/roubachof/Sharpnado.TaskLoaderView/files/5414408/Sharpnado.TaskLoaderView.2.2.0.nupkg.zip)

**Comment by clifzero** [comment]
HI @roubachof , will do so as soon as I get a chance bud, thanks a million in advance. 😃

**Comment by roubachof** [comment]
You're welcome :)
I will start working the sample app to feature new additions next week, for a release planned in 2 weeks.

**Comment by roubachof** [comment]
@PauchardThomas @Cliffy786 any news ?

**Comment by clifzero** [comment]
Hi @roubachof 

I hope you're well bud, my sincerest apologies for the extremely late response, I'm very wrong for leaving you hanging like this, it won't happen again.

I used the sample and updated the nuget package to _2.2.1_. There's a cast exception that happen's on the following line of code 

`Loader = new TaskLoaderNotifier<List<Datam>>(GetUsersAsync);`

That line of code is located in the constructor of the MainPage which I first navigate to in the sample.

**Comment by roubachof** [comment]
Sorry I don't see how I can help with such little information.

**Comment by roubachof** [comment]
Since I don't have feedback on the particular issue (TaskLoaderCommand CanExecute) dating from november, I'm closing it.

**Comment by clifzero** [comment]
Hey @roubachof !
I hope you're doing great :) I just saw this in my mail box.
I'm sorry I didn't provide enough information , could you please tell what else you need to be able to investigate. 

just in case, the [sample](https://www.dropbox.com/s/aeezua1ol7u3rj5/sample_application.zip?dl=0) I'm referring to in my previous comment was the sample I initially provided a link to.

**Comment by roubachof** [comment]
Hey man!
Sorry for saying this, but there are so many thing weird in your code :)
I guess you should look more closely to my samples view models of these projects:

* https://github.com/roubachof/Sharpnado.HorizontalListView
* https://github.com/roubachof/Xamarin-Forms-Practices

And even the retronado sample.
For example, you are using a IsBusy property whereas the whole point of the TaskLoaderView is to "free yourself from IsBusy=true" :)

**Comment by clifzero** [comment]
No offense taken, thank you for the constructive  criticism.
Did the sample at least help you replicate the issue I mentioned?
